server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservices
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: HOTEL-SERVICE

#  profiles:
#    config: prod

  config:
    import: optional:configserver:http://localhost:9091


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka



okta:
  oauth2:
    issuer: https://dev-77584981.okta.com/oauth2/default
    audience: api://default

