server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratingservices

  application:
    name: RATING-SERVICE

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


#  profiles:
#    config: prod

  config:
    import: optional:configserver:http://localhost:9091


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#     defaultZone: http://localhost:8761/eureka


